### ISSUE TITLE
tag.pattern is not recognized in .svu.yml

### ISSUE THREAD

**Issue by gotson** [caarlos0/svu#198]
Not sure if this is a feature request or bug, i let you decide :)

i usually use svu like this: `svu --tag.pattern="v[0-9]*" --tag.prefix ''`

I would like to setup my `.svu.yml` file like so:

```yml
tag:
  prefix: ""
  pattern: "v[0-9]*"
```

It works for `tag.prefix` now in 3.1.0, but not for `tag.pattern`.
