### ISSUE TITLE
Issues on Gitlab-ci

### ISSUE THREAD

**Issue by bitbreakr** [caarlos0/svu#74]
Hello, I can't make it work on my gitlab pipeline.

At a certain point in my pipeline (let's say the release job), i'm running the the following command:
```sh
curl -sfL https://install.goreleaser.com/github.com/caarlos0/svu.sh | bash -s -- -b /usr/local/bin
 ```  

All i get is an exit code 1  and it prevents next commands to be executed (see screenshot)
<img width="1134" alt="Screenshot 2022-04-28 at 18 05 06" src="https://user-images.githubusercontent.com/3123986/165796206-f5fbd728-2dc8-477d-a495-d29229524eb8.png">

Since it is erroring and exiting, i cannot tag neither create a release

```yml
release:build:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [ '' ]
  only:
    - main
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    -  curl -sfL https://install.goreleaser.com/github.com/caarlos0/svu.sh | bash -s -- -b /usr/local/bin
    - git tag $(svu next)
    - goreleaser release --rm-dist
```

What am I doing wrong ?

Thanks
